### ISSUE TITLE
Error - missing 'data/pca_pri.npy'

### ISSUE THREAD

**Issue by ofirkris** [Juyong/CaricatureFace#1]
Hi, thanks for your work.
I tried running it with the pre-trained weights - and got the following error:

`python3 train.py --no_train`

> FileNotFoundError: [Errno 2] No such file or directory: 'data/pca_pri.npy'

Can you add the missing npy file?

**Comment by RainbowRui** [comment]
Thanks for your question.
I have already put some Download Links in Section 'Advanced Work' of  'README.md', containing the file you need. You can download them through Google Drive or Baidu Drive.

**Comment by RainbowRui** [comment]
> Hi, thanks for your work.
> I tried running it with the pre-trained weights - and got the following error:
> 
> `python3 train.py --no_train`
> 
> > FileNotFoundError: [Errno 2] No such file or directory: 'data/pca_pri.npy'
> 
> Can you add the missing npy file?

Thanks for your question.
I have already put some Download Links in Section 'Advanced Work' of 'README.md', containing the file you need. You can download them through Google Drive or Baidu Drive.

**Comment by ofirkris** [comment]
Thanks, now it works - where can I add my own 224px images as input and run inference on them?

**Comment by RainbowRui** [comment]
> Thanks, now it works - where can I add my own 224px images as input and run inference on them?

I have already prepared some examples, which are also included in Section 'Advanced Work' of 'README.md'. You can download them as a reference. If you want to retrain, you have to prepare groundtruth 68 landmarks and groundtruth vertices' coordinates of 3D meshes.

**Comment by RainbowRui** [comment]
> Thanks, now it works - where can I add my own 224px images as input and run inference on them?

In addition, if you want to use other data as training set, you don't need to use 224px images as input, but need to prepare groundtruth 68 landmarks and 3D meshes which have the same structure as 'data/sub_mesh.obj' (annotated in 'train_options.py'). If you just want to test and don't have groundtruth landmarks, you can set 68 landmarks as zeros(68, 2), because they only work for calculating errors.
