### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/pca_pri.npy'

### ISSUE THREAD

**Issue by match08** [Juyong/CaricatureFace#10]
FileNotFoundError: [Errno 2] No such file or directory: 'data/pca_pri.npy'

**Comment by match08** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'data/logR_S_mean.npy'

**Comment by RainbowRui** [comment]
Please follow the ''Advanced Work'' part and download data from the link.
