### ISSUE TITLE
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1

### ISSUE THREAD

**Issue by brazilgithub** [Juyong/CaricatureFace#11]
I receive this erro. What to do?

Traceback (most recent call last):
  File "train.py", line 29, in <module>
    opt.model1_path, opt.model2_path)
  File "D:\Anaconda\Caricature\cariface.py", line 145, in load_model
    ck1 = torch.load(model1_path)
  File "C:\Users\BrenoSilva\.conda\envs\Cariface\lib\site-packages\torch\serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\BrenoSilva\.conda\envs\Cariface\lib\site-packages\torch\serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "C:\Users\BrenoSilva\.conda\envs\Cariface\lib\site-packages\torch\serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "C:\Users\BrenoSilva\.conda\envs\Cariface\lib\site-packages\torch\serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\BrenoSilva\.conda\envs\Cariface\lib\site-packages\torch\serialization.py", line 132, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\BrenoSilva\.conda\envs\Cariface\lib\site-packages\torch\serialization.py", line 126, in validate_cuda_device
    device, torch.cuda.device_count()))
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

**Comment by RainbowRui** [comment]
Thanks for your attention.
You could try to change codes in lines 145 and 146 of "cariface.py" as below:
`ck1 = torch.load(model1_path, map_location='cuda:0')`
and
`ck2 = torch.load(model2_path, map_location='cuda:0')`
You can modify the number '0' to your existing device.
This may help you.

**Comment by RainbowRui** [comment]
#2 As https://github.com/Juyong/CaricatureFace/issues/2#issuecomment-620937671

**Comment by brazilgithub** [comment]
> Thanks for your attention.
> You could try to change codes in lines 145 and 146 of "cariface.py" as below:
> `ck1 = torch.load(model1_path, map_location='cuda:0')`
> and
> `ck2 = torch.load(model2_path, map_location='cuda:0')`
> You can modify the number '0' to your existing device.
> This may help you.

Thanks for the quick response. It looks like it worked. How do I create a caricature of my own images?

**Comment by brazilgithub** [comment]
> > Thanks for your attention.
> > You could try to change codes in lines 145 and 146 of "cariface.py" as below:
> > `ck1 = torch.load(model1_path, map_location='cuda:0')`
> > and
> > `ck2 = torch.load(model2_path, map_location='cuda:0')`
> > You can modify the number '0' to your existing device.
> > This may help you.
> 
> Thanks for the quick response. It looks like it worked. I've this code:

`result: 5.934883        time: 2.1429905891418457s
        loss_land: 5.934883`

How do I create a caricature of my own images?

**Comment by RainbowRui** [comment]
Firstly, you can crop your images as the images in the test set (notice the proportion of faces), then resize them to size (224, 224). Secondly, by imitating the examples, you can make some files as "exp/test_images.txt" (the path of the origin images), "exp/test_landmarks.txt" (the path of the origin landmarks), "exp/test_lrecord.txt" (the path to save predicted landmarks) and "exp/test_vrecord.txt" (the path to save predicted vertex). Thirdly, run `bash test.sh` to obtain the predicted data. At last, follow the part "Recover 3D faces" to recover the 3D caricatures.

**Comment by brazilgithub** [comment]
Thanks! Where do I take off my real images? In which folder?


> 1. You can crop your images as the images in the test set (notice the proportion of faces), then resize them to size (224, 224).
> 2. By imitating the examples, you can make some files as "exp/test_images.txt" (the path of the origin images), "exp/test_landmarks.txt" (the path of the origin landmarks), "exp/test_lrecord.txt" (the path to save predicted landmarks) and "exp/test_vrecord.txt" (the path to save predicted vertex).
> 3. Run `bash test.sh` to obtain the predicted data.
> 4. Follow the part "Recover 3D faces" to recover the 3D caricatures.

**Comment by RainbowRui** [comment]
You can put your images in any folder, just replace the paths in "exp/test_images.txt" and "exp/test_landmarks.txt" to yours. If you have not the ground-truth landmarks, you can set all landmarks to `numpy.zeros((68, 2), np.float32)`.

**Comment by brazilgithub** [comment]
Thank you for your quick reply. How do I produce the files landmarks?

Where I set all landmarks to numpy.zeros((68, 2), np.float32)?

**Comment by RainbowRui** [comment]
Like the examples in the test set, you have to provide the ground-truth landmarks as the files in the "exp/test_landmarks.txt". However, if you could not provide, you can set the all origin landmarks to 0 (`numpy.zeros((68, 2), np.float32)`). The landmarks are only used to calculate the errors.

**Comment by brazilgithub** [comment]
Where I set all landmarks to "numpy.zeros((68, 2), np.float32)"? A file? I really dont know. Thanks, one more time!

**Comment by RainbowRui** [comment]
Each landmarks-related file in our testset ("Advanced Work - Prepare some examples" link) is a (68, 2) tensor. When you use pretrained model to predict, we can set them to 0. Because you don't know the ground-truth landmarks of your own images.

**Comment by RainbowRui** [comment]
You can set all the landmarks in our examples ("Advanced Work - Prepare some examples" link) to 0 and have a try, it shows that our method do not need the ground-truth landmarks when using pretrained model, because the ground-truth landmarks are only used to calculate errors.

**Comment by brazilgithub** [comment]
> You can set all the landmarks in our examples ("Advanced Work - Prepare some examples" link) to 0 and have a try, it shows that our method do not need the ground-truth landmarks when using pretrained model, because the ground-truth landmarks are only used to calculate errors.

Well, it seems a bit complicated to me. I'm not a programmer. Could you provide a step by step, or some video tutorial?

**Comment by RainbowRui** [comment]
That's all right. Maybe you can try our algorithm on our examples (see the link of "**Advanced Work - Prepare some examples**") firstly. Then look over the related files in the examples. At last, you can comprehend what I said before.
