### ISSUE TITLE
Test Result using exp data is not pretty well..

### ISSUE THREAD

**Issue by CodingMice** [Juyong/CaricatureFace#14]
I test the pretrained model with the exp data, but I do not get good enough result. Is there something wrong?
![0](https://user-images.githubusercontent.com/22537112/103122153-272c2d00-46ba-11eb-99a9-5e197069273a.jpg)
![1](https://user-images.githubusercontent.com/22537112/103122158-2bf0e100-46ba-11eb-9875-b02fe9f75db8.jpg)
![2](https://user-images.githubusercontent.com/22537112/103122163-2eebd180-46ba-11eb-8c4c-41b4464a22bb.jpg)
![3](https://user-images.githubusercontent.com/22537112/103122166-301cfe80-46ba-11eb-9e50-5f67ad3c9794.jpg)
![4](https://user-images.githubusercontent.com/22537112/103122170-31e6c200-46ba-11eb-99de-6949a9c55294.jpg)

**Comment by RainbowRui** [comment]
It looks something wrong. Are you sure you used the correct process to obtain and draw the landmarks on the images?

**Comment by CodingMice** [comment]
I use the cafiface.py by the command "python train.py --no_train". After that, I got npyfile of lands_2d, and show it in the image using opencv.

**Comment by RainbowRui** [comment]
I just checked it again. Here are my results for reference (use the pretrained model in my google drive).
![2a7a46104330addb2d3e6777f78856b5](https://user-images.githubusercontent.com/39452932/103221094-ccfec680-495c-11eb-8611-eedae0c7edeb.jpg)
![2ce107af39f648273c311ad60040d429](https://user-images.githubusercontent.com/39452932/103221102-cec88a00-495c-11eb-87d4-e766d20106ae.jpg)
![2ef62a8b57c2473f54e484aae4c45232](https://user-images.githubusercontent.com/39452932/103221106-cff9b700-495c-11eb-84fd-87561221e3f0.jpg)
![4c4a9dd2fc7bbf84f12f899570baefa3](https://user-images.githubusercontent.com/39452932/103221110-d1c37a80-495c-11eb-8753-44f9d09e0aff.jpg)
![6d355efa2ad357ac370deb2fb9b1da63](https://user-images.githubusercontent.com/39452932/103221115-d425d480-495c-11eb-957f-32e89e976097.jpg)

**Comment by RainbowRui** [comment]
Please use "sh test.sh" instead of "python train.py --no_train", because the latter one does not use the pretrained model.

**Comment by CodingMice** [comment]
I check that "python train.py --no_train" can use the pretrained model. BTW, I have tested it in Win10 system, and my pytorch version is 1.2.0. Does it make any differences?

**Comment by RainbowRui** [comment]
Maybe the mistake happened during the visualization, I find the color of these images are wrong.

**Comment by CodingMice** [comment]
The color is caused by saving image in RGB. That makes no differences.   I use the visualization as your answer in "https://github.com/Juyong/CaricatureFace/issues/8"

**Comment by RainbowRui** [comment]
This is my "draw_lands.py" file:
```
import cv2
import numpy as np
import random
whole_num = 5
image_path = './images/'
lands_path = './lrecord/'
img_list_path = './test_images.txt'
target_path = './img_with_lands/'

file = open(img_list_path, 'r')
img_name_list = file.readlines()
file.close()
for i in range(whole_num):
    name_ = img_name_list[i].strip('\n')

    img_file_name = image_path + name_ + '.jpg'
    lands_file_name = lands_path + name_ + '_l.npy'
    target_file_name = target_path + name_ + '.jpg'

    img = cv2.imread(img_file_name)

    lands = np.load(lands_file_name)
    lands = np.rint(lands).astype(int)

    for j in range(68):
        cv2.circle(img, (lands[j,0], lands[j,1]), 1, (0,255,0), 2)

    cv2.imwrite(target_file_name, img)

    print(i)
```
The "test_images.txt" I used is:
```
2a7a46104330addb2d3e6777f78856b5
2ef62a8b57c2473f54e484aae4c45232
6d355efa2ad357ac370deb2fb9b1da63
2ce107af39f648273c311ad60040d429
4c4a9dd2fc7bbf84f12f899570baefa3
```
You can take a look!

**Comment by RainbowRui** [comment]
This is my 'lrecord/' files which are created from the pretrained model of the proposed method.
[lrecord.zip](https://github.com/Juyong/CaricatureFace/files/5749803/lrecord.zip)

**Comment by CodingMice** [comment]
Thanks a lot. I find that the lrecord I got is different from your lrecord.  Your lrecord is nice results. So maybe there is something wrong in the test processing.

**Comment by RainbowRui** [comment]
Yes, please directly use the codes without modification.
