### ISSUE TITLE
Recovering 3D Face Mesh

### ISSUE THREAD

**Issue by zhaoyuanyuan2011** [Juyong/CaricatureFace#18]
Hi,

I'm trying to explore the project by running the code and getting the outputs. I've successfully generate images with landmarks drawn on them. According to the paper, the next step should be to generate the 3D face mesh. I notice that in toy_example, it has 2 python files that converts a .npy file to a .obj file and the other way as well. I assume that in order to generate the 3D face mesh, we need a .npy file that is previously generated during the process of detecting landmarks. May I ask how to find the .npy file if my assumption is correct?

Thank you!

**Comment by RainbowRui** [comment]
Your assumption is correct. You can find vertex file ('.npy' file) in './record/vrecord/' folder after getting the outputs.

**Comment by zhaoyuanyuan2011** [comment]
> Your assumption is correct. You can find vertex file ('.npy' file) in './record/vrecord/' folder after getting the outputs.

Thank you so much!
