### ISSUE TITLE
Get wrong result

### ISSUE THREAD

**Issue by mingsjtu** [Juyong/CaricatureFace#19]
I crop and resize the images in your dataset to 224, and run test.sh using the pretrained model but get the error result.

Could you tell me where did I make a mistake?

**Comment by RainbowRui** [comment]
You can follow the "Prepare some examples" section of "Advanced Work" part to try the pretrained model on our data. Then crop, resize the images as our data shown (the face must occupy most of the image and in the center of the image as much as possible), and try again.
