### ISSUE TITLE
FittingIndicesPlus() function 

### ISSUE THREAD

**Issue by Easy-Shu** [Juyong/CaricatureFace#20]
Hi, thansk for your great work. But I have a problem about function of 
FittingIndicesPlus(euler_angle, scale, trans, points, parallel, best_51):
#V_NUM              the number of vertices
#euler_angle        a euler_angle tensor with size (m,3)
#scale              a scale tensor with size (m,1)
#trans              a translation matrix with size (m,2)
#points             a point tensor with size (m,3,V_NUM)
#parallel           a long tensor with size (17,4), you can read it from './parallel.txt' file.
#best_51            a long tensor with size (51), which represents the last 51 landmarks (68-17=51).

Can you provide a sample of vertices? When I use the exsiting mean_face.obj and /parallel.txt to visualize it, I found the landmark display is not right:
![image](https://user-images.githubusercontent.com/60866625/117579593-39b57900-b126-11eb-89ad-b71bb1fb0cee.png)

**Comment by RainbowRui** [comment]
Thanks for your attention! Maybe you can follow the process shown in Fig.4 of our paper "Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model", then use some softwares (such as Blender, OpenFlipper) to label the optional silhouette landmarks by your own. Thanks again!
