### ISSUE TITLE
No such file or directory : ...

### ISSUE THREAD

**Issue by farzadmohseni-ir** [Juyong/CaricatureFace#21]
# When running train.py

**The errors you see were fixed by renaming .**

**How do I fix the last error ?**

![image](https://user-images.githubusercontent.com/57835828/118775716-760e7500-b89c-11eb-9f48-69c091045a0f.png)

**Comment by RainbowRui** [comment]
Thanks for your attention! You can follow the "Advanced Work" part of README to prepare some examples.
