### ISSUE TITLE
how do I get the full head mesh?

### ISSUE THREAD

**Issue by yutaka329** [Juyong/CaricatureFace#23]
Nice works,  I want to recover the head mesh from the submesh, Can you share the vertices of submesh in original head mesh?
Thanks a lot.

**Comment by pptrick** [comment]
Hi, have you figured out a way to do this? I'm doing the same thing too.

**Comment by RainbowRui** [comment]
Maybe you could do a registration from submesh to head mesh.

**Comment by whl32611** [comment]
> Nice works, I want to recover the head mesh from the submesh, Can you share the vertices of submesh in original head mesh? Thanks a lot.

Hi, have you figured out a way to do this? I'm doing the same thing too.
