### ISSUE TITLE
code typo

### ISSUE THREAD

**Issue by subinium** [Juyong/CaricatureFace#25]
There seems to be a typo in layer initialization. 

https://github.com/subinium/CaricatureFace/blob/af96d6acdc5178ba4ab68ea4ab0f7f0f968aeb6b/cariface.py#L65

``` py
torch.nn.init.kaiming_normal_(self.fc1.weight.data) # fc1 -> fc2
```

**Comment by RainbowRui** [comment]
Thanks! I have revised it!
