### ISSUE TITLE
cal error

### ISSUE THREAD

**Issue by mingsjtu** [Juyong/CaricatureFace#30]
When I try to evalute your results on the testest provided by you in [Google Drive](https://drive.google.com/open?id=1fGHlV8ISUkgCK8OSTQxvEJxtxXXrwjDI)
Use python cal_error/cal_error.py

The results is 
the mean error: 5.822952259763909
the mean error(pupil): 0.08047147811848179
the mean error(ocular): 0.054439231366942696
the mean error(diagnal): 0.024300979350562503

Why is it so different from the Table 1 in your paper?

**Comment by RainbowRui** [comment]
Since the testset prepared in Google Drive is a toy dataset for evaluation, which is different from our large testset shown in our paper.
