### ISSUE TITLE
How to get the landmarks?

### ISSUE THREAD

**Issue by pptrick** [Juyong/CaricatureFace#31]
Hi, thanks for your great work! 
I notice that a landmark file (.npy) for a caricature image is required for testing (test.sh), However, I don't know how to get these labels.  Should I label it manually, or is there a way to generate landmarks?

**Comment by RainbowRui** [comment]
The ground-truth 2D landmarks are just for evaluation (such as calculating metrics). You can set them to a zero tensor with size of (68, 2). But you need to crop your own caricature manually to the size that have a similar face proportion as our examples shown.

**Comment by RainbowRui** [comment]
Since our method is for landmark detection, but not 2d face detection, it requires a reasonable proportion of the face region in the whole region. Best wishes!

**Comment by pptrick** [comment]
Thank you for your super quick response! I'll try if it works.
