### ISSUE TITLE
.npy file convert to .obj mesh looks wrong

### ISSUE THREAD

**Issue by ghost** [Juyong/CaricatureFace#32]
I'm sorry i ask the question in the email yesterday,    I run the project on win 10. 
![12](https://user-images.githubusercontent.com/17847750/147747340-1a40aa46-d01f-490b-8214-753579d8d9c3.png)
     today,  i install a ubuntu18.04,and the question remains.
I download CariFace_data.zip,CariFace_model.zip and CariFace_exp.zip then extract to directory ./CaricatureFace/data, ./CaricatureFace/model and ./CaricatureFace/exp.  run command    python train.py  --no_train. 

in the cariface.py file at line 346, i add code:
mesh = om.read_trimesh("mean_face.obj")
vertex = points.reshape(3,self.vertex_num).data.cpu().numpy()
for i in range(6144):
     mesh.points()[i] = vertex[:, i]
om.write_mesh(str(vrecord[0])+".obj", mesh)
![12](https://user-images.githubusercontent.com/17847750/147748078-8fade636-e81e-4906-867a-a8887aa1de13.png)

**Comment by RainbowRui** [comment]
Hello, I just copy your code in my workflow, I find the result is correct. Maybe you need to examine whether the related variables (like 'points') have been modified.
![Screenshot from 2021-12-30 19-58-13](https://user-images.githubusercontent.com/39452932/147750025-59d15228-01b4-4307-82a8-9080984cc52d.png)
![Screenshot from 2021-12-30 20-00-21](https://user-images.githubusercontent.com/39452932/147750146-94776714-a2cf-42d3-81e9-46622ce1e1d4.png)

**Comment by RainbowRui** [comment]
[3D_results.zip](https://github.com/Juyong/CaricatureFace/files/7792819/3D_results.zip)
You can see from this file.

**Comment by ghost** [comment]
I'm surprised all file from github or baidu Drive.

**Comment by RainbowRui** [comment]
It looks strange. Maybe check the version of openmesh software?

**Comment by ghost** [comment]
To remember，For some reason, I installed the following version，Could  be the reason？
torch_1.10.1+cu113 
torchaudio_0.10.1+cu113
torchvision_0.11.2+cu113
openmesh_1.1.6

**Comment by RainbowRui** [comment]
So I do not analyze what error is. If you save '.npy' file then use code to obtain '.obj', is the result great?

**Comment by NaNillll** [comment]
I find the same problem. I also save '.npy' file generated by test.sh and get mesh using  mesh_to_vertex.py. The fianl mesh is wrong, similar to yours. I don't kown why......

**Comment by NaNillll** [comment]
I also try to just visualize point as point cloud before get mesh, and the result is also wrong, just a mess...

**Comment by NewtOliver** [comment]
I find the same problem. What to do to solve this problem？
