### ISSUE TITLE
.obj file looks wrong

### ISSUE THREAD

**Issue by NewtOliver** [Juyong/CaricatureFace#38]
my linux environment：

torch：1.11.0+cu113             
torchaudio： 0.11.0+cu113            
torchvision： 0.12.0+cu113
cuda：11.3

![image](https://user-images.githubusercontent.com/45253712/158531156-1f0d814d-67e9-4f5e-a9b6-624355a9cbf8.png)

**Comment by RainbowRui** [comment]
Hello, maybe you can see this: https://github.com/Juyong/CaricatureFace/issues/35#issue-1129973351

**Comment by RainbowRui** [comment]
If the version of pytorch is changed, it needs to convert the pretrained model (.pt or .pth file) under current version.
