### ISSUE TITLE
Can this model show good results on reconstructing real face?

### ISSUE THREAD

**Issue by NaNillll** [Juyong/CaricatureFace#39]
My goal is  to interpolate between real face and its caricture face in 3D. And I want to first reconstruct these two face, and interpolate between their latent vector, then reconstruct using it.
However, when I test, I find this model seems not reconstruct real face very well. In principle, it shouldn't, because the real face is also a type of caricature. 
Have you tested this before? Maybe there is someting with my experiment.
Thank you!

**Comment by NaNillll** [comment]
![image](https://user-images.githubusercontent.com/48055162/159173363-73c6f2ee-83d4-496f-a247-6593a3b5d07d.png)
![image](https://user-images.githubusercontent.com/48055162/159173381-3ae0b84b-28a8-47bc-8fa5-332b1cc31e15.png)
![image](https://user-images.githubusercontent.com/48055162/159173387-94349e41-c859-435b-8ad5-4906422e4536.png)
![image](https://user-images.githubusercontent.com/48055162/159173496-9f2740e3-b5bb-4e3b-a7a7-40daf06fe546.png)

Some examples. I reconstrcut this faces and porject landmarks back on 2D images. As it shows, the  landmarks seems not very accurate...

And the 3D model, also not very good...
![image](https://user-images.githubusercontent.com/48055162/159173654-373168ae-2bfc-44ee-a5f9-ec28e8e4f5b9.png)

**Comment by RainbowRui** [comment]
Deep-learning based methods always depend on training dataset. If you need to reconstruct 3D real faces using our method, you may prepare your own real face dataset and retrain the model. Besides, our proposed deformation representation is more suitable for highly exaggerated geometry (caricature-liked/cartoon-liked) than normal geometry (real face).

**Comment by NaNillll** [comment]
I know，thank you！

**Comment by RainbowRui** [comment]
You are welcome!

**Comment by NaNillll** [comment]
Hello. Now I want to train CaricatureFace also on real face dataset so that I can interpolate between real face and its caricture face in 3D. But I don't know how to get the real faces matching the CaricatureFace since the the  number and order of face-points using in CaricatureFace have fixed. For example, if I want to train CaricatureFace on BFM face dataset (53490 vertexs) , what should I do? The paper just says that the dataset is construct using "Alive Caricature from 2D to 3D" and I can't find  more details......
I'm a new hand and don't know much about face reconstruction,  could you please give me some guidance?  Thanks！

**Comment by RainbowRui** [comment]
If you would like to use deformation feature to fit 3D face shape, I recommend you to follow this paper ([ACAP: Sparse Data Driven Mesh Deformation, Gao et al.](http://geometrylearning.com/paper/sparse2019.pdf)). If you want to reconstruct real face, I recommend you to consider linear parametrical model - 3DMM-like, such as [FLAME](https://flame.is.tue.mpg.de/).
