### ISSUE TITLE
Can I know how to crop caricature image?

### ISSUE THREAD

**Issue by wonjongJ** [Juyong/CaricatureFace#4]
Thanks for your nice research!

When I run your code, I figured out that the result changes according to how to crop caricature image. So, I will be really grateful if you inform me how you cropped caricature image.

**Comment by RainbowRui** [comment]
@wonjongJ You can refer to function **clip_rot_flip_face(image, landmarks, scale, alpha)** of **datagen.py**, the input contain an arbitrary image, its ground-truth 68 landmarks, the size of clipping and angle of rotation (you can set it as 0). This is the way I choose to crop images.

**Comment by wonjongJ** [comment]
Oh, I missed it. I will see and check it. Thank you! :)
