### ISSUE TITLE
 landmarks files 

### ISSUE THREAD

**Issue by hulonghua** [Juyong/CaricatureFace#40]
Hello, I'm a novice, how can I reconstruct my comic pictures? Do the landmarks files in the code need to be generated by themselves?

**Comment by RainbowRui** [comment]
You can crop your comic pictures (to insure that the proportion of facial region as our paper and proposed dataset shown). Then use our pretrained model to test, you do not need to label 2D landmarks' positions.

**Comment by hulonghua** [comment]
你好，请教一下，我尝试使用预训练模型测试我的漫画图片，因为为没有landmarks文件，这里出现了错误，我不是很明白不使用landmarks怎么对漫画图片完成测试，我在您的数据集和测试例子中都看到了landmarks文件。
![image](https://user-images.githubusercontent.com/31496909/160224644-c68c765c-5f76-41ca-bdde-ea44af2381a8.png)

**Comment by RainbowRui** [comment]
在测试中，这只用于计算误差，不会参与网络模块的推理。因此可以把gt landmarks相关代码去掉，或者新建一些68*2的零向量（与图片命名对应）npy文件。

**Comment by hulonghua** [comment]
喔喔，感谢，我后面去读代码的时候发现landmarks 没参与计算，只是算误差，然后我就把相关代码，注释掉了，现在已经生成 结果了，非常感谢🙏。
