### ISSUE TITLE
run test on my image

### ISSUE THREAD

**Issue by kruzel** [Juyong/CaricatureFace#42]
can you explain how to run a test on my image?

**Comment by RainbowRui** [comment]
Hi, you can follow [this guidance](https://github.com/Juyong/CaricatureFace/issues/34) and have a try!

**Comment by kruzel** [comment]
hi @RainbowRui ,

**Comment by kruzel** [comment]
hi @RainbowRui , thank you for your fast reply,
I followed your guidance cropped my image to 224x224 and run.
this is how the images folder looks like
<img width="465" alt="image" src="https://user-images.githubusercontent.com/975963/177474473-4523118f-b9ca-4634-a0fa-2f1df6f3e8ee.png">

but when running I get this error:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/975963/177474563-85651dab-b311-46dc-90b7-a03fe530648d.png">

I see all images in your example have compatible landmarks, do I need to add that? how?

**Comment by RainbowRui** [comment]
Hi, the detected or labelld landmarks are just for error calculation. Maybe you can comment related codes out or just create a file containing a zero tensor with the same size of our examples and having a same name with corresponding jpg file.

**Comment by kruzel** [comment]
hi,
I copied one of the npy files under landmark and renames to same name as
image.
also add to landmarks txt file.
but still doesn't work.

Ofer Kruzel
M: +972 (54) 4516627

**Comment by kruzel** [comment]
had to add line to last_lrecord.txt and last_vrecord.txt,
not train test.sh working
