### ISSUE TITLE
visualize deformed 3D mesh from image

### ISSUE THREAD

**Issue by kruzel** [Juyong/CaricatureFace#43]
I succeeded to run test.sh,
but now I wan to see the mesh result, 
can you explain how to do that?

**Comment by RainbowRui** [comment]
Hi, you can follow [Recover 3D faces in ReadMe](https://github.com/Juyong/CaricatureFace#recover-3d-faces)

**Comment by RainbowRui** [comment]
Before it, please make sure using the correct pytorch version, with the reason of [a previous issue](https://github.com/Juyong/CaricatureFace/issues/35)

**Comment by kruzel** [comment]
succeeded
