### ISSUE TITLE
some confused work with data

### ISSUE THREAD

**Issue by min-star** [Juyong/CaricatureFace#47]
hello,the caricatureface work is great,i am very intersted with it ,I checked the readme,run and debug the code.some file from data dir confused me a few days!I am a new at the field,can you guide me with how to generate the pca_pri.npy,logR_S_meana.npy and A_pinv.npy,i am looking forward you reply,Senior!

**Comment by RainbowRui** [comment]
The meaning of 'pca_pri.npy' and 'logR_S_mean.npy' correspond to the 2nd paragraph in Part C of our paper (Principal Component Analysis based on the training database). 'A_pinv.npy' is a inverse matrix of cotangent weight of the template mesh, corrsponding to the 3rd paragraph in Part B.

> hello,the caricatureface work is great,i am very intersted with it ,I checked the readme,run and debug the code.some file from data dir confused me a few days!I am a new at the field,can you guide me with how to generate the pca_pri.npy,logR_S_meana.npy and A_pinv.npy,i am looking forward you reply,Senior!

**Comment by min-star** [comment]
Thanks for your help!Maybe i should read the paper once again,some concept are clear!great!
