### ISSUE TITLE
How to generate train data?

### ISSUE THREAD

**Issue by CodingMice** [Juyong/CaricatureFace#5]
Nice jobs. I am instreasted in the process of making train data. Will you share the code?

**Comment by RainbowRui** [comment]
Thanks for your attention. The ground truth data are created by the algorithm based on the article "Alive caricature from 2d to 3d". I will try to share a copy of source code or a copy of an executable with the consent of the author of that article in the future.

**Comment by jingwang97** [comment]
I have read these two papers and I am also very interested in the algorithm proposed in the article"Alive caricature from 2d to 3d".
Will you share the code?I will very appreciate it if you agree.Thanks a lot!

**Comment by RainbowRui** [comment]
> I have read these two papers and I am also very interested in the algorithm proposed in the article"Alive caricature from 2d to 3d".
> Will you share the code?I will very appreciate it if you agree.Thanks a lot!

However, the paper "Alive caricature from 2d to 3d" is not mine.
