### ISSUE TITLE
How to generate relate data

### ISSUE THREAD

**Issue by steventai0212** [Juyong/CaricatureFace#6]
if i want use my own training data, how can i generate the relate data
Thanks a lot.

**Comment by RainbowRui** [comment]
Thanks for your attention. However, one related data is based on the training set (do PCA on the ground truth meshes) which created by the algorithm based on the article "Alive caricature from 2d to 3d". I will try to share a copy of source code or a copy of an executable with the consent of the author of that article in the future.

**Comment by steventai0212** [comment]
Thanks a lot. That is pretty nice work!

**Comment by RainbowRui** [comment]
You are welcome!

**Comment by whl32611** [comment]
> Thanks for your attention. However, one related data is based on the training set (do PCA on the ground truth meshes) which created by the algorithm based on the article "Alive caricature from 2d to 3d". I will try to share a copy of source code or a copy of an executable with the consent of the author of that article in the future.

Hello, did you get permission of releasing the code of pca part?
