### ISSUE TITLE
How can I find the file which is named"data/pca_pri.npy"?

### ISSUE THREAD

**Issue by 123-sweatheart** [Juyong/CaricatureFace#7]
I tried to duplicate your code, but I encountered an error:Error 2.No such file or dictionary:'data/pca_pri.npy'.
So could you help me solve this problem? Thanks a lot.

**Comment by RainbowRui** [comment]
Please follow the "Advanced Work" part and download the related data.

**Comment by 123-sweatheart** [comment]
Thanks, now it works.
