### ISSUE TITLE
结果可视化

### ISSUE THREAD

**Issue by zhuqianqian-judy** [Juyong/CaricatureFace#8]
您好，我是刚接触这个研究方面，我按照您GitHub上的操作步骤，最终得出的结果是loss_land：5.934936 ，我想请教一下，怎么让测试图片 的可视化呢？

**Comment by RainbowRui** [comment]
You can put 68 landmarks (a (68,2) tensor) on the image like this:
```
import cv2
import numpy as np

img = cv2.imread("ori.jpg")
lands = np.loadtxt("landmarks.jpg.txt")
lands = np.rint(lands).astype(int)
for i in range(68):
    cv2.circle(img, (lands[i][0], lands[i][1]), 2, (0,255,0), -1)
    cv2.imwrite("with_lands.jpg",img)
```

**Comment by zhuqianqian-judy** [comment]
我用您代码中的五张图片，我想得到最终可视化的漫画图片，就像您文章中的fig1的原始2D漫画+3D模型+2Dlandmarks图片，这个可视化结果。这个也是按照您上一条回复的code去做吗？因为我最终的目的是需要换成WebCaricatures数据集（只取5张2D漫画照片和每张照片只有17个landmarks的npy文件//）中几张照片，来测试一下最终的结果。

**Comment by RainbowRui** [comment]
可以参考这个代码将预测的关键点可视化：
```
import cv2
import numpy as np

img = cv2.imread("ori.jpg")
lands = np.loadtxt("landmarks.jpg.txt")
lands = np.rint(lands).astype(int)
for i in range(17):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (255,0,0), 2)
for i in range(17,22):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (255,0,255), 2)
for i in range(22,27):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (180,110,255), 2)
for i in range(27,31):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (0,255,0), 2)
for i in range(31,36):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (34,139,34), 2)
for i in range(36,42):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (0,255,255), 2)
for i in range(42,48):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (29,102,205), 2)
for i in range(48,68):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (0,0,255), 2)
cv2.imwrite("with_lands.jpg",img)
```
3D模型的重建可参考仓库中的 "Recover 3D faces" 模块。

**Comment by RainbowRui** [comment]
3D模型的可视化是用meshlab或者blender之类的软件打开obj文件，然后截图得到的。

**Comment by zhuqianqian-judy** [comment]
好的，非常感谢您的耐心回复。后面有问题的话还可能会再次打扰您，祝好。

**Comment by RainbowRui** [comment]
祝好！有时间我会及时解答的。

**Comment by RainbowRui** [comment]
代码输出的loss只是参考，比较算法的话还需要在较大的数据集上用不同的metric衡量，有时间我会把这个项目做得更完善的。祝好！

**Comment by zhuqianqian-judy** [comment]
我把您给的原文件2a7a46104330addb2d3e6777f78856b5.jpg.npy文件转成如下格式的txt文件，部分例如：
143.72  365.966
140.756 438.567
145.201 509.686
140.756 579.323
161.499 656.369
... ...

运行您昨天给的这个code，我改了自己的路径

`import cv2
import numpy as np

img = cv2.imread("/home/zqq/project/CaricatureFace-master/exp/images/2a7a46104330addb2d3e6777f78856b5.jpg")
lands = np.loadtxt("/home/zqq/project/CaricatureFace-master/exp/landmarks/2a7a46104330addb2d3e6777f78856b5.jpg.txt")
lands = np.rint(lands).astype(int)
for i in range(17):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (255,0,0), 2)
for i in range(17,22):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (255,0,255), 2)
for i in range(22,27):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (180,110,255), 2)
for i in range(27,31):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (0,255,0), 2)
for i in range(31,36):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (34,139,34), 2)
for i in range(36,42):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (0,255,255), 2)
for i in range(42,48):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (29,102,205), 2)
for i in range(48,68):
    cv2.circle(img, (lands[i][0], lands[i][1]), 1, (0,0,255), 2)
cv2.imwrite("/home/zqq/project/CaricatureFace-master/exp/with_lands.jpg",img)`


但我最终得到结果图with_lands.jpg是原图像，没有得到您文章中带有Landmark的标记点的漫画图。这是怎么回事呢？先感谢您的回复。

**Comment by zhuqianqian-judy** [comment]
有结果了，是我把文件弄错了，再次感谢您的耐心回复。向您学习。祝好。

**Comment by whl32611** [comment]
您好，请问您得到的结果是有颜色的mesh吗？有没有把贴图做到模型上去呢？

**Comment by RainbowRui** [comment]
您好，可以根据网格投影到图片上的对应关系给网格上色。

**Comment by RainbowRui** [comment]
> 您好，请问您得到的结果是有颜色的mesh吗？有没有把贴图做到模型上去呢？

您好，可以根据网格投影到图片上的对应关系给网格上色。

**Comment by whl32611** [comment]
>感谢您的回复，我想知道一下这个在您的代码里面有实现过吗？

**Comment by whl32611** [comment]
> > 您好，请问您得到的结果是有颜色的mesh吗？有没有把贴图做到模型上去呢？
> 
> 您好，可以根据网格投影到图片上的对应关系给网格上色。

感谢您的回复，我想知道一下这个在您的代码中有实现过吗？我看论文中是有的，这部分可以分享一下吗？谢谢！

**Comment by RainbowRui** [comment]
> > > 您好，请问您得到的结果是有颜色的mesh吗？有没有把贴图做到模型上去呢？
> > 
> > 
> > 您好，可以根据网格投影到图片上的对应关系给网格上色。
> 
> 感谢您的回复，我想知道一下这个在您的代码中有实现过吗？我看论文中是有的，这部分可以分享一下吗？谢谢！

这部分没有放到这个project中哈。实现方案就是通过网格顶点在图片上的投影像素值给它的颜色赋值，您可以尝试下。

**Comment by whl32611** [comment]
> 

好的我试试！
